# Generated by Django 4.2.3 on 2023-07-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6)),
                ('fromID', models.CharField(max_length=50)),
                ('msg', models.CharField(blank=True, max_length=1024, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('H', 'Hab'), ('S', 'Station'), ('P', 'Person')], max_length=1, null=True)),
                ('sensor_data', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
