# Generated by Django 4.2.3 on 2023-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mqttmsg_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dId', models.CharField(max_length=50, unique=True)),
                ('last_msg', models.CharField(blank=True, max_length=50, null=True)),
                ('last_sensor_data', models.CharField(blank=True, max_length=5000, null=True)),
                ('alert', models.BooleanField(default=False)),
            ],
        ),
    ]
