# Generated by Django 4.2.3 on 2023-07-15 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_mqttmsg_device_type_device_last_ping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_ping",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 20, 26, 42, 581479)
            ),
        ),
    ]
